### ISSUE TITLE
Modify validation for telephone-numbers>number

### ISSUE THREAD

**Issue by Telos-sa** [metaschema-framework/oscal-cli#33]
# User Story:

We have outlined the user story and goals for this enhancement on [NIST OSCAL Repo issue 2041](https://github.com/usnistgov/OSCAL/issues/2041)

There are validation constraints the oscal-cli uses for telephone-numbers>number that are not outlined in the [OSCAL SSP json schema](https://github.com/usnistgov/OSCAL/releases/download/v1.1.2/oscal_ssp_schema.json)

## Acceptance Criteria

- [ ] All website and readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by iMichaela** [comment]
@Telos-sa - in general none of the OSCAL constraints are implemented in the schemas because it is not possible. The Schematron rules were used for the OSCAL XML to validate the artifacts and insure the constraints are following the OSCAL Reference (documentation).

I am not sure what is the purpose of this issue. @Telos-sa - could you please clarify the expectations? Thank you.

**Comment by Telos-sa** [comment]
@iMichaela I guess we're just confused with where these constraints are coming from and how we could apply them programmatically. I understand that this is all covered in the outline on the link you provided - we are very familiar with this resource.

The concern is how will we be able to programmatically implement these constraints in the module we've created for exporting OSCAL. We currently leverage the JSON schemas for the different models - so our hope is that these various constraints for specific fields could be represented in the schemas somehow.

**Comment by david-waltermire** [comment]
@Telos-sa These are defined in the [OSCAL Metaschemas](https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_metadata_metaschema.xml#L1044) as a built-in constraint. 

Here is an excerpt:

```xml
<allowed-values allow-other="yes">
  <enum value="home">A home phone number.</enum>
  <enum value="office">An office phone number.</enum>
  <enum value="mobile">A mobile phone number.</enum>
</allowed-values>
```

Because this is `allow-other="yes"`, which means any value can be used, it is not possible to check for one of a set of given values.

In general, some things can be expressed in JSON schema, but others are not easily or possible to express in JSON or XML schema. We use constraints for these, which supports validation in addition to schema validation. For the extra-schema validation case, you have a few choices for how to do this in your tooling:

1) Call OSCAL CLI to perform the checks, processing the results (which are now in SARIF) making this easier.
2) Implement Metaschema constraint processing and checking to do something similar to what OSCAL CLI does.
3) Implement the constraints as code in your tool.
