### ISSUE TITLE
Certain prop>values have constraints that are not outlined in OSCAL SSP json schema

### ISSUE THREAD

**Issue by Telos-sa** [metaschema-framework/oscal-cli#34]
# User Story:

User story and goals are outlined in [NIST OSCAL Repo issue 2042](https://github.com/usnistgov/OSCAL/issues/2042)

There are several props that have constraints that are not outlined in the [OSCAL SSP json schema](https://github.com/usnistgov/OSCAL/releases/download/v1.1.2/oscal_ssp_schema.json)

Some examples of these props are system-characteristics>props>name="cloud-service-model"&name="cloud-deployment-model" and system-implementation>components>props>name="isa-date".

## Acceptance Criteria

- [ ] All website and readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire** [comment]
Please see #33 for an explanation of why it's not always possible to represent some validation rules in XML or JSON schema, and why Metaschema constraints are used for extra schema validation.

Regarding the props mentioned here and in usnistgov/OSCAL#2042, the use of props in OSCAL is a primary extension mechanism. Since a prop can have an arbitray namespace, name, and value (among other flags), these flag values are constrained using Metaschema constraints. 

For example:
- system-characteristics>props>name="cloud-service-model"&name="cloud-deployment-model" is [defined in the SSP Metaschema module](https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_ssp_metaschema.xml#L152).
- system-implementation>components>props>name="isa-date" is defined in the implementation common Metaschema module ([location 1](https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_implementation-common_metaschema.xml#L193) and [location 2](https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_implementation-common_metaschema.xml#L213)), which is used by multiple OSCAL models.

In many cases (including those above), the restriction implemented by a constraint applies when the name and namespace have a specific value, which requires logic that is not present in JSON and XML schema.

As a result, this issue cannot be addressed.
